
CREATE DATABASE [Zombie];
GO

USE [Zombie]
GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'TableA' AND TABLE_SCHEMA = 'dbo')
    drop table dbo.TableA;

CREATE TABLE [dbo].[TableA] (
	[Key] [nvarchar](50) NOT NULL,
	[Value] [nvarchar](max) NOT NULL,
 	CONSTRAINT [PK_TableA] PRIMARY KEY CLUSTERED ([Key] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'TableB' AND TABLE_SCHEMA = 'dbo')
    drop table dbo.TableB;
GO

CREATE TABLE [dbo].[TableB] (
	[Id] [uniqueidentifier] ROWGUIDCOL NOT NULL,
	[Sequence] [bigint] IDENTITY(1,1) NOT NULL,
	[Key] [varchar](50) NULL,
	[Value] [varchar](max) NULL,
	CONSTRAINT [PK_TableB] PRIMARY KEY CLUSTERED ([Id] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

CREATE NONCLUSTERED INDEX [TableB_Key] ON [dbo].[TableB] ([Key] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)