
IF (EXISTS (SELECT name 
FROM master.dbo.sysdatabases 
WHERE ('[' + name + ']' = '[Zombie]')))
BEGIN
	USE master;
	ALTER DATABASE [Zombie] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [Zombie] ;
END 

CREATE DATABASE [Zombie];
GO
ALTER DATABASE [Zombie] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Zombie].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Zombie] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Zombie] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Zombie] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Zombie] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Zombie] SET ARITHABORT OFF 
GO

ALTER DATABASE [Zombie] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Zombie] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Zombie] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Zombie] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Zombie] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Zombie] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Zombie] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Zombie] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Zombie] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Zombie] SET DISABLE_BROKER 
GO

ALTER DATABASE [Zombie] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Zombie] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Zombie] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Zombie] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [Zombie] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Zombie] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Zombie] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Zombie] SET RECOVERY FULL 
GO

ALTER DATABASE [Zombie] SET  MULTI_USER 
GO

ALTER DATABASE [Zombie] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Zombie] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Zombie] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Zombie] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Zombie] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Zombie] SET  READ_WRITE 
GO

USE [Zombie]
GO
if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'TableA' AND TABLE_SCHEMA = 'dbo')
    drop table dbo.TableA;

/****** Object:  Table [dbo].[TableA]Script Date: 24/02/2020 10:12:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TableA] (
	[Key] [nvarchar](50) NOT NULL,
	[Value] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_TableA] PRIMARY KEY CLUSTERED 
(
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

USE [Zombie]
GO

/****** Object:  Table [dbo].[TableB]   Script Date: 24/02/2020 10:12:01 AM ******/
if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'TableB' AND TABLE_SCHEMA = 'dbo')
    drop table dbo.TableB;
GO
/****** Object:  Table [dbo].[TableB]   Script Date: 24/02/2020 10:09:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TableB] (
	[Id] [uniqueidentifier] ROWGUIDCOL NOT NULL,
	[Sequence] [bigint] IDENTITY(1,1) NOT NULL,
	[Key] [varchar](50) NULL,
	[Value] [varchar](max) NULL,
CONSTRAINT [PK_TableB] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [Zombie]
GO

/****** Object:  Index [TableB_Key]    Script Date: 24/02/2020 11:36:24 AM ******/
CREATE NONCLUSTERED INDEX [TableB_Key] ON [dbo].[TableB]
(
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



SET ANSI_PADDING ON
GO

----

USE [Zombie]
GO

SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

GO
